/*
 * linux/fs/hfsplus/richacl.h
 *
 * Vyacheslav Dubeyko <slava@dubeyko.com>
 *
 * Handler for NFSv4 Access Control Lists (ACLs) support.
 */

#ifndef _LINUX_HFSPLUS_RICHACL_H
#define _LINUX_HFSPLUS_RICHACL_H

#include <linux/richacl.h>

/* HFS+ Access Control List Entry (ACE) flags */
#define HFSPLUS_ACE_KINDMASK		0xf
#define HFSPLUS_ACE_PERMIT		1
#define HFSPLUS_ACE_DENY		2
#define HFSPLUS_ACE_AUDIT		3
#define HFSPLUS_ACE_ALARM		4
#define HFSPLUS_ACE_INHERITED		(1<<4)
#define HFSPLUS_ACE_FILE_INHERIT	(1<<5)
#define HFSPLUS_ACE_DIRECTORY_INHERIT	(1<<6)
#define HFSPLUS_ACE_LIMIT_INHERIT	(1<<7)
#define HFSPLUS_ACE_ONLY_INHERIT	(1<<8)
#define HFSPLUS_ACE_SUCCESS		(1<<9)
#define HFSPLUS_ACE_FAILURE		(1<<10)

/* All flag bits controlling ACE inheritance */
#define HFSPLUS_ACE_INHERIT_CONTROL_FLAGS \
		(HFSPLUS_ACE_FILE_INHERIT | \
		 HFSPLUS_ACE_DIRECTORY_INHERIT | \
		 HFSPLUS_ACE_LIMIT_INHERIT | \
		 HFSPLUS_ACE_ONLY_INHERIT)

/* HFS+ Access Control List Entry (ACE) rights */
#define HFSPLUS_VNODE_READ_DATA			(1<<1)
#define HFSPLUS_VNODE_LIST_DIRECTORY		HFSPLUS_VNODE_READ_DATA
#define HFSPLUS_VNODE_WRITE_DATA		(1<<2)
#define HFSPLUS_VNODE_ADD_FILE			HFSPLUS_VNODE_WRITE_DATA
#define HFSPLUS_VNODE_EXECUTE			(1<<3)
#define HFSPLUS_VNODE_SEARCH			HFSPLUS_VNODE_EXECUTE
#define HFSPLUS_VNODE_DELETE			(1<<4)
#define HFSPLUS_VNODE_APPEND_DATA		(1<<5)
#define HFSPLUS_VNODE_ADD_SUBDIRECTORY		HFSPLUS_VNODE_APPEND_DATA
#define HFSPLUS_VNODE_DELETE_CHILD		(1<<6)
#define HFSPLUS_VNODE_READ_ATTRIBUTES		(1<<7)
#define HFSPLUS_VNODE_WRITE_ATTRIBUTES		(1<<8)
#define HFSPLUS_VNODE_READ_EXTATTRIBUTES	(1<<9)
#define HFSPLUS_VNODE_WRITE_EXTATTRIBUTES	(1<<10)
#define HFSPLUS_VNODE_READ_SECURITY		(1<<11)
#define HFSPLUS_VNODE_WRITE_SECURITY		(1<<12)
#define HFSPLUS_VNODE_TAKE_OWNERSHIP		(1<<13)

#define HFSPLUS_ACE_GENERIC_ALL			(1<<21)
#define HFSPLUS_ACE_GENERIC_EXECUTE		(1<<22)
#define HFSPLUS_ACE_GENERIC_WRITE		(1<<23)
#define HFSPLUS_ACE_GENERIC_READ		(1<<24)

#define HFSPLUS_VNODE_ANYONE_MODE (HFSPLUS_VNODE_READ_ATTRIBUTES | \
					 HFSPLUS_VNODE_READ_EXTATTRIBUTES | \
					 HFSPLUS_VNODE_READ_SECURITY)

#define HFSPLUS_VNODE_GENERIC_READ_BITS (HFSPLUS_VNODE_READ_DATA | \
					 HFSPLUS_VNODE_READ_ATTRIBUTES | \
					 HFSPLUS_VNODE_READ_EXTATTRIBUTES | \
					 HFSPLUS_VNODE_READ_SECURITY)

#define HFSPLUS_VNODE_OWNER_MODE (HFSPLUS_VNODE_WRITE_ATTRIBUTES | \
					 HFSPLUS_VNODE_WRITE_EXTATTRIBUTES | \
					 HFSPLUS_VNODE_WRITE_SECURITY)

#define HFSPLUS_VNODE_WRITE_MODE (HFSPLUS_VNODE_WRITE_DATA | \
					  HFSPLUS_VNODE_APPEND_DATA | \
					  HFSPLUS_VNODE_DELETE)

#define HFSPLUS_VNODE_GENERIC_WRITE_BITS (HFSPLUS_VNODE_WRITE_DATA | \
					  HFSPLUS_VNODE_APPEND_DATA | \
					  HFSPLUS_VNODE_DELETE | \
					  HFSPLUS_VNODE_DELETE_CHILD | \
					  HFSPLUS_VNODE_WRITE_ATTRIBUTES | \
					  HFSPLUS_VNODE_WRITE_EXTATTRIBUTES | \
					  HFSPLUS_VNODE_WRITE_SECURITY)

#define HFSPLUS_VNODE_GENERIC_EXECUTE_BITS (HFSPLUS_VNODE_EXECUTE)

#define HFSPLUS_VNODE_GENERIC_ALL_BITS	(HFSPLUS_VNODE_GENERIC_READ_BITS | \
					 HFSPLUS_VNODE_GENERIC_WRITE_BITS | \
					 HFSPLUS_VNODE_GENERIC_EXECUTE_BITS)

#ifdef CONFIG_HFSPLUS_FS_RICHACL

#define HFSPLUS_IS_RICHACL(inode) IS_RICHACL(inode)

extern struct richacl *hfsplus_get_richacl(struct inode *);
extern int hfsplus_init_richacl(struct inode *, struct inode *);
extern int hfsplus_richacl_chmod(struct inode *);

#else  /* CONFIG_HFSPLUS_FS_RICHACL */

#define HFSPLUS_IS_RICHACL(inode) (0)
#define hfsplus_get_richacl   NULL

static inline int hfsplus_init_richacl(struct inode *inode, struct inode *dir)
{
	return 0;
}

static inline int hfsplus_richacl_chmod(struct inode *inode)
{
	return 0;
}

#endif  /* CONFIG_HFSPLUS_FS_RICHACL */
#endif  /* _LINUX_HFSPLUS_RICHACL_H */
